### ISSUE TITLE
u3d install updating cache even with --no-download option

### ISSUE THREAD

**Issue by niezbop** [DragonBox/u3d#104]

**Comment by lacostej** [comment]
We need to add a parameter like: `offline: false` to the cache?

**Comment by niezbop** [comment]
Well, the cache is not needed when `--no-download`. So I think it shouldn't be called at all. An `offline` option for the cache that contains urls make little sense in my opinion

**Comment by lacostej** [comment]
cache also used for mapping latest to a version number.

```ruby
        cache = Cache.new(force_os: os)
        cache_versions = cache[os.id2name]['versions']
        version = interpret_latest(version, cache_versions)
        unless cache_versions[version]
          UI.error "No version '#{version}' was found in cache. Either it doesn't exist or u3d doesn't know about it yet. Try refreshing with 'u3d available -f'"
          return
        end
```

**Comment by niezbop** [comment]
In my opinion, this is a bad idea as it leads to non-deterministic behaviour where `latest` is the latest discovered version which means that it would not match the same version depending on the user computer.

Furthermore, I'm not sure this supports a real usecase. The `--no-download option` is made for people who want to DL specific versions and install them later or people which will move installer files from a machine to another. In both of this cases, I think that they will probably not use the `latest` keyword.

**Comment by lacostej** [comment]
When you run in offline mode, you are controlling what is in your environment. 
It is deterministic based on your environment. I think it still does what you expect. I.e. download the latest I know of. It's even more deterministic than when you run install latest without updating the cache.

I made a PR to propose a solution. It would require a couple of tests to ensure things are working as they should. In particular, I don't like the exception handling and returned `nil` values in the cache.

**Comment by niezbop** [comment]
Reviewed you PR!
