### ISSUE TITLE
Build fail on linux

### ISSUE THREAD

**Issue by niezbop** [DragonBox/u3d#110]

**Comment by lacostej** [comment]
@niezbop Do you have more information as to what fails?

I fired a linux cloud machine, and managed to install dev tools, bundle install the deps, and run the tests

![image](https://user-images.githubusercontent.com/24282/29902249-2725657a-8dfd-11e7-97d4-38914b9d6d4a.png)

![image](https://user-images.githubusercontent.com/24282/29902240-17f22282-8dfd-11e7-8978-db8ec68534d4.png)

**Comment by niezbop** [comment]
It was an issue with my version. Upgraded and it works fine.
```
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
activesupport-5.1.3 requires ruby version >= 2.2.2, which is incompatible with the current version, ruby 2.1.5p273
```

That's something we should be aware of nonetheless.

**Comment by lacostej** [comment]
Closing for now
