### ISSUE TITLE
[QUESTION] u3d install through TeamCity (mac)

### ISSUE THREAD

**Issue by marklonquist** [DragonBox/u3d#148]
Hi

Don't know where else to ask, but when using "u3d install" it asks for root permissions - How would you input this through a CI like TeamCity?

Thanks in advance :-)

**Comment by lacostej** [comment]
Hello @marklonquist, you have several options

* pass the password using U3D_PASSWORD environment variable

* if on Mac, use the keychain option (you set it before hand on the machine, e.g. from the command line using `u3d credentials add` (use `u3d credentials check` to verify) and then use `u3d install -k` to enable the keychain use.

**Comment by marklonquist** [comment]
I'm getting an error trying  to use `u3d credentials add` 
```
BigMac-Byggefar:~ byggefar$ u3d credentials add --trace
/Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.4/lib/u3d/commands.rb:180:in `credentials': unknown keyword: options (ArgumentError)
	from /Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.4/lib/u3d/commands_generator.rb:171:in `block (2 levels) in run'
	from /Users/byggefar/.rvm/gems/ruby-2.4.1/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/byggefar/.rvm/gems/ruby-2.4.1/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/byggefar/.rvm/gems/ruby-2.4.1/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/byggefar/.rvm/gems/ruby-2.4.1/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/byggefar/.rvm/gems/ruby-2.4.1/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.4/lib/u3d/commands_generator.rb:195:in `run'
	from /Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.4/lib/u3d/commands_generator.rb:37:in `start'
	from /Users/byggefar/.rvm/gems/ruby-2.4.1@global/gems/u3d-1.0.4/exe/u3d:7:in `<main>'
BigMac-Byggefar:~ byggefar$
```

Am I missing anything? :-) It does show help when I do `u3d credentials --help` so I guess it should be in the GEM I'm using.

**Comment by niezbop** [comment]
This is an issue! Thank you so much for reporting it. I'm writing a fix.

**Comment by marklonquist** [comment]
Using U3D_PASSWORD until it's fixed :-)

**Comment by niezbop** [comment]
Okok. @lacostej should provide feedback on my PR soon, and it should be fixed in a couple of hours!
