### ISSUE TITLE
u3d/list => Not detecting unity list in windows 10 under linux subsystem

### ISSUE THREAD

**Issue by brunocapdevila** [DragonBox/u3d#150]
```
root@DESKTOP-JILKEAS:/mnt/c/Users/bcapd# irb
irb(main):001:0> pqth=File.join('C:/Program Files', 'Unity')
=> "C:/Program Files/Unity"
irb(main):002:0> Dir[pqth]
=> []
irb(main):003:0> Dir['C:/']
=> []
irb(main):004:0> Dir['/mnt/c']
=> ["/mnt/c"]
irb(main):005:0> Dir['/mnt/c/Program Files']
=> ["/mnt/c/Program Files"]
irb(main):006:0> Dir['/mnt/c/Program Files/Unity']
=> ["/mnt/c/Program Files/Unity"]
irb(main):007:0> Dir['/mnt/c/Program Files/Unity/**/Editor/Uninstall.exe']
=> ["/mnt/c/Program Files/Unity/2017.1.0f3/Editor/Uninstall.exe", "/mnt/c/Program Files/Unity/5.3.6f1/Editor/Uninstall.exe", "/mnt/c/Program Files/Unity/5.6.0f3/Editor/Uninstall.exe", "/mnt/c/Program Files/Unity
/5.6.1f1/Editor/Uninstall.exe"]
irb(main):008:0> Dir['/mnt/c/Program Files/Unity/*/Editor/Uninstall.exe']
=> ["/mnt/c/Program Files/Unity/2017.1.0f3/Editor/Uninstall.exe", "/mnt/c/Program Files/Unity/5.3.6f1/Editor/Uninstall.exe", "/mnt/c/Program Files/Unity/5.6.0f3/Editor/Uninstall.exe", "/mnt/c/Program Files/Unity
/5.6.1f1/Editor/Uninstall.exe"]
```

**Comment by lacostej** [comment]
@niezbop how does that work on your machine?

**Comment by niezbop** [comment]
I'm usually working on a VM to get things working, so no idea atm, but I'll try that right away.

**Comment by niezbop** [comment]
SO! Tried it and I have the exact same behaviour as @brunocapdevila. I'm not sure how we could handle that nonetheless. Any idea @lacostej?

**Comment by lacostej** [comment]
I forgot about the VM. How does that work in practice?

For this, one way is to find out which environment we are in, and go from there, but searching a different path. I am not even sure if the Ubuntu system identifies this as a Window or Linux system.

I will check tomorrow

**Comment by niezbop** [comment]
I partitionned my disk, so I can start a Linux on this. It has very limited link to the Windows architecture.

I checked the environnemnent quickly this morning:
![capture d ecran 245](https://user-images.githubusercontent.com/16774018/30898354-478d5bf6-a35b-11e7-81cf-94494a0d9b77.png)

**Comment by niezbop** [comment]
So that may be a bit complicated to get around.

**Comment by lacostej** [comment]
@brunocapdevila can you try running this in your bash?

```
ruby -e 'require "rubygems"; require "u3d"; puts "#{RUBY_PLATFORM} #{U3dCore::Helper.operating_system}"'
```

Thanks!

**Comment by niezbop** [comment]
`RUBY_PLATFORM` is `x86_64-linux-gnu` on mine

**Comment by niezbop** [comment]
Closing this issue as we do not support Bash on Ubuntu on Windows for the moment. See #155 for further detail.
