### ISSUE TITLE
u3d/install: already installed packages are reinstalled

### ISSUE THREAD

**Issue by lacostej** [DragonBox/u3d#161]
This is because modules have different names in ini and locally. Right?

**Comment by niezbop** [comment]
Indeed. When we detect installed packages we do it on a name basis and this name is different than the one in the ini files, and therefore no correspondance.

**Comment by lacostej** [comment]
Investigated a bit.

Here are the list of modules of the 2017.3.0b7 available on the INI file: 
```
Android AppleTV Documentation Example Facebook-Games Linux Mac MonoDevelop Samsung-TV StandardAssets Tizen Unity Vuforia-AR WebGL WebPlayer Windows iOS
```
Here are the list of modules detected by u3d after install of all modules of 2017.3.0b7
```
Android Facebook StandaloneLinux StandaloneWindows UnityExtensions WebGL iPhone tvOS
```

There are several issues
* the names are different
* some modules are installed in different ways (no ivy.xml)
* some are non existent (e.g. WebPlayer)
* the above is maybe platform specific

Not really sure we are going to spend time doing this.
