### ISSUE TITLE
Linux CLI Activation in Unity >= 5.4

### ISSUE THREAD

**Issue by brianmxwll** [DragonBox/u3d#176]
Does this application provide any workaround for activating a Unity install for version 5.4 or greater? A standard install cannot currently authenticate a license via CLI & -username, -password, -serial (for Linux, at least).  

https://forum.unity.com/threads/5-4-0p1-fails-to-launch-due-to-license.425277/

**Comment by lacostej** [comment]
I think the last time I tried something like that on a headless server, I installed xfvb. Have you tried something like that?

**Comment by brianmxwll** [comment]
Yeah, the issue appears to be the lack of ability to actually "confirm" the license via the command line. If you use xfvb or some other method of letting the GUI render, the license registration still times out. The only method I'm aware of (total hack) is to install VNC, register license via GUI, then use the CLI normally. This is less than ideal for creating a docker setup where builds can run automatically... it's impossible to share an image without passing along your Unity license. 

If u3d is just an installation manager and passes along CLI arguments, I would expect the issue to be the same. If that's the case, no worries - just figured I'd ask if you had a way around it.

**Comment by lacostej** [comment]
@brianmxwll Is this because you are running the personal edition? My understanding is that you should be able to do what you want with the pro version and `batchmode`.

I'll close this issue as it is not a u3d issue per se, but feel free to keep the thread on if you want :)

**Comment by brianmxwll** [comment]
Nah, it happens to personal and non-personal editions. Thanks for the time!
