### ISSUE TITLE
can't force a specific version of unity to run

### ISSUE THREAD

**Issue by Duobix** [DragonBox/u3d#179]
Hi, 
it seems that u3d has no way of forcing a specific unity version to run, or am I missing something?
"u3d run" doesn't take version as a parameter. 
That might come in handy if someone used the wrong editor version by accident.

**Comment by niezbop** [comment]
Hey!

There is an option for that! You can run `u3d run -u whateverversion`.

If you're unsure about a command, you can do `u3d whatevercommand -h` to display the associated help menu.

I hope it helps!

**Comment by niezbop** [comment]
I'm closing this issue as there is already a solution to this :)

**Comment by lacostej** [comment]
@Duobix note that every command is self documented. E.g.
```u3d run --help```

![image](https://user-images.githubusercontent.com/24282/32322651-88bb2492-bfc5-11e7-87a6-83bbda4c17f8.png)
