### ISSUE TITLE
u3d/install: confusing "-p not available on linux" message

### ISSUE THREAD

**Issue by makslevental** [DragonBox/u3d#181]
`u3d available -p` shows Unity as a package but then the installer warns that `-p | --packages not available for Linux`. I'm also curious why package installs aren't available on linux since they are possible through the gui?

**Comment by makslevental** [comment]
ah i get it you're scraping from here for example https://unity3d.com/unity/whats-new/unity-2017.2.0

**Comment by lacostej** [comment]
@makslevental Are packages install now supported on Linux? My understanding is that Linux only support the full installation.

See https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/ and http://beta.unity3d.com/download/ee86734cf592/public_download.html for the current latest build.

**Comment by makslevental** [comment]
@lacostej i guess you're right about it being all-inclusive. cheers
