### ISSUE TITLE
Unity version not found when run from u3d fastlane plugin

### ISSUE THREAD

**Issue by Woody4618** [DragonBox/u3d#188]
Hey, 

I installed it and every thing works fine, i can also build and run unity tests as long as i use u3d. 

But when i try the fastlane plugin it never finds my installed unity version any idea? 

I ran u3d list and it showed me all installed versions. I tried Unity_2017.1.1f1 and 2017.1.1f1. same result.

This is my fast lane:

lane :test do
  u3d(
    unity_version: "Unity_2017.1.1f1",
    run_args: '-some cool parameters'
  )
end

 
The output:
 
[18:13:03]: -------------------------------------------------
[18:13:03]: --- Step: Verifying required fastlane version ---
[18:13:03]: -------------------------------------------------
[18:13:03]: Your fastlane version 2.64.1 matches the minimum requirement of 2.28.9  ✅
[18:13:03]: ------------------------------
[18:13:03]: --- Step: default_platform ---
[18:13:03]: ------------------------------
[18:13:03]: Driving the lane 'test' 🚀
[18:13:03]: -----------------
[18:13:03]: --- Step: u3d ---
[18:13:03]: -----------------
+------------------+------+
|      Lane Context       |
+------------------+------+
| DEFAULT_PLATFORM | ios  |
| PLATFORM_NAME    |      |
| LANE_NAME        | test |
+------------------+------+
[18:13:04]: Unity version '["Unity_2017.1.1f1"]' not found

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | u3d                                 | 0           |

 If i run without the unity_version set i get:
[20:16:51]: Not sure which version of Unity to run. Are you in a project?

The fastlane file use is not within the unity project.

Also if i run the plugin without any parameter i get this error:
NoMethodError: [!] undefined method `scan' for nil:NilClass
  /Users/jonasmac/.rbenv/versions/2.4.2/lib/ruby/2.4.0/shellwords.rb:82:in `shellsplit'
  /Users/jonasmac/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-plugin-u3d-

Greetings,
Jonas

**Comment by lacostej** [comment]
@Woody4618 
1. the version should be `'2017.1.1f1'` and not `'Unity_2017.1.1f1'`.
2. if it doesn't find the unity version of your Unity project, could you check your project layout? It should be like this: https://github.com/DragonBox/u3d/tree/master/examples/Example2 i.e.
```
Assets/
ProjectSettings/ProjectVersion.txt
fastlane/Fastfile
```
if you have no parameter then it should fail, maybe with a better error message :)

**Comment by Woody4618** [comment]
I did use the right version 2017.1.1f1 and it did not work. 
The problem was that the fastlane file was not within the project, like you said. I got it working like this now. 

lane :test do
  u3d(
    run_args: '-projectpath /Users/jonasmac/pathToMyProject'
  )
end

Thanks

**Comment by lacostej** [comment]
@Woody4618 Cool

An alternative is I think to use ruby's
```
Dir.chdir('your/project/dir') do
  u3d(....)
end
```
