### ISSUE TITLE
`u3d list` not detecting previous Unity install (Linux)

### ISSUE THREAD

**Issue by garyritchie** [DragonBox/u3d#189]
...5.6.2xf1 Linux (64bit) from previous "manual" install from deb package.

Ubuntu 16.10
u3d 1.0.10
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

```bash
/opt/Unity/Editor$ u3d list --verbose
WARN No Unity version installed
```

So it's not detecting the v5.6 like it does on Windows -- which is pretty awesome, Thanks!

**Comment by lacostej** [comment]
@garyritchie I improved the list heuristic to take into account where the debian package installs its version. Feel free to test or wait until we make a release!
