### ISSUE TITLE
Do we need X11 Library ?

### ISSUE THREAD

**Issue by zukinaru** [DragonBox/u3d#197]
Hi, i want to install u3d on VPS (ubuntu), Do we need X11 Library like Xvfb ?

Thanks

**Comment by lacostej** [comment]
Hello, u3d is ruby. But Unity has its own dependencies. They are listed on the patch page.

You can install them using `u3d dependencies`.

I have run successfully u3d on circleci using this method: https://github.com/lacostej/u3d_ci_example/blob/master/Rakefile  Also it is not practical as the installation time is cost prohibitive.

**Comment by zukinaru** [comment]
Hi,

it's because i have try to use Jenkins before, but they need X11/Xvfb before run correctly, but always failed...

**Comment by lacostej** [comment]
@zukinaru It all depends on you run Unity. I believe it can run in headless mode. See https://medium.com/@h0lycattle/running-unity3d-in-a-virtualized-headless-ubuntu-environment-1adf95c05994
