### ISSUE TITLE
UWP-IL2CPP package not available on mac?

### ISSUE THREAD

**Issue by bdovaz** [DragonBox/u3d#199]
If I list available packages for:

2017.1.2f1
2017.2.1f1
2017.3.0f3

It doesn't appear and I can't install it.

**Comment by lacostej** [comment]
@bdovaz  Not sure about UWP-IL2CPP. Is this supposed to be contained in the Windows subpackage?

```
$ u3d available  -p -u 2017.3.0f3
Version 2017.3.0f3: https://netstorage.unity3d.com/unity/a9f86dcd79df/
Packages:
 - Unity
 - MonoDevelop
 - Documentation
 - StandardAssets
 - Example
 - Android
 - iOS
 - AppleTV
 - Linux
 - Vuforia-AR
 - WebGL
 - Windows
 - Facebook-Games
```

If not then it would seem that Unity installs this in a different way than the other modules. Maybe using Packman? Do you have more information?

**Comment by bdovaz** [comment]
In Windows installer is listed as UWP-IL2CPP.

Maybe it's only available on Windows platform because it uses Windows SDK.

**Comment by niezbop** [comment]
Hey!

It looks like it is available for Windows, but not on Mac:

```
C:\Users\Paul>u3d available -p -u 2017.1.2f1 -o win
Version 2017.1.2f1: https://download.unity3d.com/download_unity/cc85bf6a8a04/
Packages:
 - Unity
 - Documentation
 - StandardAssets
 - Example
 - VisualStudio
 - VisualStudioProfessionalUnityWorkload
 - VisualStudioEnterpriseUnityWorkload
 - FacebookGameroom
 - Android
 - iOS
 - AppleTV
 - Linux
 - Mac
 - Metro
 - UWP-IL2CPP
 - Samsung-TV
 - Tizen
 - WebGL
 - Facebook-Games

C:\Users\Paul>u3d available -p -u 2017.1.2f1 -o mac
Version 2017.1.2f1: https://download.unity3d.com/download_unity/cc85bf6a8a04/
Packages:
 - Unity
 - Documentation
 - StandardAssets
 - Example
 - Android
 - iOS
 - AppleTV
 - Linux
 - Samsung-TV
 - Tizen
 - WebGL
 - Windows
 - Facebook-Games
```

It would seem that this is due to the SDK indeed, but I can't be sure. Could this be an error on our side @lacostej ?

**Comment by lacostej** [comment]
@niezbop @bdovaz I suspect it is not available on Mac. The ini doesn't mention it.

**Comment by bdovaz** [comment]
Ok, thanks.
