### ISSUE TITLE
Jenkins, OSX and privileges

### ISSUE THREAD

**Issue by bdovaz** [DragonBox/u3d#200]
I see that you use it in your own company with CI.

Do you know if there is any way to run a command without user interaction?

I want in a job to run:

sh 'u3d install 2017.1.2f1 -p WebGL'

So I can be always sure that before running Unity the required version and platforms are installed.

**Comment by lacostej** [comment]
@bdovaz the doc is at https://github.com/DragonBox/u3d#reuse-u3d-install-on-a-ci-environment

We will update the inlined help to reflect this information.

**Comment by bdovaz** [comment]
Thanks, sorry, I didn't saw that.

In my case it was as simple as this:

`withCredentials([string(credentialsId: 'mac_keychain', variable: 'U3D_PASSWORD')]) {
    sh "u3d install 2017.1.2f1 -p WebGL";
}`

**Comment by lacostej** [comment]
Great. When you are done, feel free to contribute to https://github.com/DragonBox/u3d/blob/master/docs/ci_setup.md

Thanks!
