### ISSUE TITLE
Error : "error: Not sure which version of Unity to run. Are you in a Unity5 or later project?. Use --trace to view backtrace"

### ISSUE THREAD

**Issue by zukinaru** [DragonBox/u3d#204]
Hi,

i have install unity for linux manually and place it on /opt/unity-editor-2017.3.0f1

by running `u3d list` i got below list : 
**Version 2017.3.0f1                    (/opt/unity-editor-2017.3.0f1)**

but running `u3d run` i got below error :
**error: Not sure which version of Unity to run. Are you in a Unity5 or later project?. Use --trace to view backtrace**

How to choose unity version to run ?

thanks in advance...

**Comment by lacostej** [comment]
From `u3d run --help`

```
    -u, --unity_version STRING 
        Version of Unity to run with. If not specified, it runs with the version of the project (either specified as -projectpath or current)
```

**Comment by zukinaru** [comment]
Hi, thanks for fast reply. 
now i think it's running...
