### ISSUE TITLE
Allow to specify packages download path

### ISSUE THREAD

**Issue by bdovaz** [DragonBox/u3d#213]
Now, at least on Windows platform it stores downloaded packages in current user "Downloads" folder.

In our organization we share a network drive where we store heavy installers and packages. When you are using it in your own machine it makes sense to go to "Downloads" folder but at least on a CI server we should be able to provide a custom path.

In our organization we would like to run a command on "u3d" to check if that Unity version and packages (platforms) are installed providing a parameter with a custom path where package checks (to see if it's already there) are done and downloads are stored.

So that way we could have downloads stored on the mentioned network drive and share Unity installers on our entire organization.

Now we download them manually and there is no coherence in folder names, etc. U3D providing coherent folder names fixes this for us.

**Comment by lacostej** [comment]
@bdovaz OK. Out of curiosity, could you specify which platforms you use u3d on, which CI server you use, and wether you use other related tools like fastlane. Thanks!

**Comment by niezbop** [comment]
Hey @bdovaz , I just opened #214 to add an option to specify the path of the download, ie doing `u3d install ... --download_path myPath` will download the installers under `myPath/Unity_Packages/<version>/`. Please feel free to leave any feedback on the pull request!

**Comment by bdovaz** [comment]
@niezbop why are you adding "Unity_Packages" subfolder? Is there any reason? Thanks!

@lacostej I have a Jenkins master on Windows Server 2012, one slave on Windows 10, another one on latest macOS and I use fastlane for Unity iOS builds (but I'm not using u3d fastlane integration).

**Comment by niezbop** [comment]
@bdovaz nous reason! It's a mistake on part! I'll change this

**Comment by lacostej** [comment]
Fixed in #214 !

**Comment by bdovaz** [comment]
@niezbop @lacostej thanks!!
