### ISSUE TITLE
Error opening default X display

### ISSUE THREAD

**Issue by zukinaru** [DragonBox/u3d#223]
Hi,

i run u3d on headless server and face below error : 

**Error opening default X display
(Filename: /home/builduser/buildslave/unity/build/Editor/Platform/Linux/X11Quarantine.cpp Line: 33)**

How to solve this ?

thanks in advance...

**Comment by lacostej** [comment]
I am not 100%. 2 options

1. use both -nographics and -batchmode
2. if that still doesn't work, add xfvb on your machine.

**Comment by zukinaru** [comment]
Hi,
it solved with -nographics

btw, do you have example build script for Android ?
