### ISSUE TITLE
u3d/available missing latest versions on Linux

### ISSUE THREAD

**Issue by IvanRibakov** [DragonBox/u3d#241]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

Running `u3d available -f` doesn't display `2017.3.0f1` and `2017.3.0p2` which are currently available on Linux platform.

Could this be due to the fact that Unity forum post https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256 now has second page at https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/page-2 ?

**Comment by lacostej** [comment]
Most probably! We will fix this :)

**Comment by lacostej** [comment]
@IvanRibakov feature released as part of 1.0.16
