### ISSUE TITLE
 Error "Cancelled 'Build.Player.AndroidPlayer'" when Building APK

### ISSUE THREAD

**Issue by zukinaru** [DragonBox/u3d#254]
### Issue Checklist

- [X ] I'm using the latest u3d version
- [X ] I ran `u3d --help`
- [X ] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [X ] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

[DESCRIBE YOUR ISSUE HERE]

Hi, thanks for let me post an issue...

i'm using : 
+Unity Personal Edition
+My Own installation of Unity 2017.3.0f1 and place it on **/opt/unity-editor-2017.3.0f1**
+Unity Build Scripts from [here](https://github.com/Anooky/unity-android-auto-build/blob/master/Assets/_scripts/Editor/BuildProject.cs), to produce an APK.

My Command when did this tasks : 

`u3d run -u 2017.3.0f1 -- -batchmode -quit -logFile build.log -nographics -batchmode -executeMethod" BuildProject.BuildAndroid" -androidSdkPath "/home/rain/android-sdk-linux" -buildOutput "/home/rain/myapps.apk" -projectPath "/home/rain/GameDev/myapps"  -buildPlatform android`

However, when i check its log, it come with below errors  :  

```
***** Cancelled 'Build.Player.AndroidPlayer' in 1 seconds (806 ms)
ERROR_CAUSED===>Error building player because build target was unsupported- Starting compile Library/ScriptAssemblies/Assem
bly-CSharp-Editor.dll
- Finished compile Library/ScriptAssemblies/Assembly-CSharp-Editor.dll**
```
any idea what caused this error ?
if because android module not installed, how to add it ?
or because it's Unity personal ?

Thanks in advance

**Comment by lacostej** [comment]
Hello @zukinaru ,

So you installed Unity on your own, so it cannot be u3d's fault for installation.

Can you run unity using the same command line and without u3d? I.e. directly invoking `/opt/unity-editor-2017.3.0f1...` with the proper command line?

**Comment by zukinaru** [comment]
Hi,
it's not problem if using unity from u3d installation, but which version does support Android. I mean, each time i try to u3d install 2017.XX Unity,Android - they dont have Android module..

**Comment by lacostej** [comment]
@zukinaru maybe you can try installing unity using their official installer and see if that works better?

https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/page-2#post-3313793

Support for the newer Linux installer in u3d is new and from last week in version 1.0.16. I haven't tested it completely yet.

**Comment by zukinaru** [comment]
Hi, 
so u3d support Android Module for Windows & MacOS ?

**Comment by lacostej** [comment]
@zukinaru my question is: does unity support the android module on 2017.3.0f1?

I haven't tested this myself.

When implementing linux packages support I only installed the modules that are packaged with .tar.xz not in .pkg (which I assumed were for Mac and an error).

See http://beta.unity3d.com/download/3c89f8d277f5/unity-2017.3.0f1-linux.ini

````
[Android]
title=Android Build Support
description=Allows building your Unity projects for the Android platform
url=MacEditorTargetInstaller/UnitySetup-Android-Support-for-Editor-2017.3.0f1.pkg
````

If you can report that 2017.3.0f1 or any other Linux version with packages does indeed propose to install a functioning Android package, then I will find a way to support .pkg installation on Linux as well.

**Comment by lacostej** [comment]
Finally took at look at this.
```
root@ubuntu-512mb-ams2-01:~# Downloads/UnitySetup-2017.4.0f1 --list-components
Error 404 getting 'https://netstorage.unity3d.com/unity/0ec691fce5c2/unity-2017.4.0f1-linux.ini'
Download of 'https://netstorage.unity3d.com/unity/0ec691fce5c2/unity-2017.4.0f1-linux.ini' failed
Error 404 getting 'http://download.unity3d.com/download_unity/0ec691fce5c2/unity-2017.4.0f1-linux.ini'
Download of 'http://download.unity3d.com/download_unity/0ec691fce5c2/unity-2017.4.0f1-linux.ini' failed
Successfully downloaded http://beta.unity3d.com/download/0ec691fce5c2/unity-2017.4.0f1-linux.ini => /tmp/.PY8OHZ
Usage:
  For default component set, do not specify --components.
  For all components: --components=All
  For select components: --components=(comma separated list)
Available components (case sensitive):
 (*) Unity: Unity Editor
 (*) Documentation: Unity User Manual and Scripting API Reference
 (*) StandardAssets: Unity Standard Assets for easily getting started building projects in Unity
 (*) Example: Unity Example Project based on Standard Assets
 (*) Android: Allows building your Unity projects for the Android platform
 (*) iOS: Allows building your Unity projects for the iOS platform
 (*) Mac: Allows building your Unity projects for the Mac platform
 (*) WebGL: Allows building your Unity projects for the WebGL platform
 (*) Windows: Allows building your Unity projects for the Windows platform
 (*) Facebook-Games: Allows building your Unity projects for the Facebook-Games platform
Key: '!' = required; '*' = selected by default.
root@ubuntu-512mb-ams2-01:~# less /tmp/.^C
```

so yes, Unity supports the .pkg. We need to support this in some way.

**Comment by lacostej** [comment]
I see that the Unity unattended installer now needs libarchive to install.

there's no xar in ubuntu

but with
```
apt-get install p7zip-full

7z -o/tmp/U e Downloads/Unity_Packages/UnitySetup-Mac-Support-for-Editor-2017.4.0f1.pkg

ls -la /tmp/U
total 39772
drwxr-xr-x  4 root root     4096 Apr 24 07:54 .
drwxrwxrwt 10 root root     4096 Apr 24 08:00 ..
-rw-r--r--  1 root root    33328 Apr 24 07:36 background.tiff
-rw-r--r--  1 root root   131229 Apr  4 14:27 Bom
-rw-r--r--  1 root root      816 Apr 24 07:36 Distribution
-rw-r--r--  1 root root      668 Apr 24 07:36 PackageInfo
-rw-r--r--  1 root root 40419852 Apr  4 14:28 Payload
-rw-r--r--  1 root root    77138 Apr  4 14:28 PlugIns
drwx------  2 root root     4096 Jan  1  1970 Resources
-rw-r--r--  1 root root      632 Apr  4 14:28 Scripts
drwx------  2 root root     4096 Jan  1  1970 TargetSupport.pkg.tmp
-rw-r--r--  1 root root    16613 Apr 24 07:36 [TOC].xml
-rw-r--r--  1 root root      818 Apr 24 07:36 Welcome.rtf


cat /tmp/U/PackageInfo

<pkg-info overwrite-permissions="true" relocatable="false" identifier="com.unity3d.MacStandaloneSupport" postinstall-action="none" version="0" format-version="2" generator-version="InstallCmds-502 (14F27)" install-location="/Applications/Unity/PlaybackEngines/MacStandaloneSupport" auth="root">

-> install-location = "/Applications/Unity/PlaybackEngines/MacStandaloneSupport"

7z l Payload


7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,1 CPU)

Listing archive: Payload

--
Path = payload
Type = Cpio

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2018-04-04 14:24:41 D....            0            0  .
2018-04-04 14:10:36 .....          413          413  ./ivy.xml
2018-04-04 14:05:41 D....            0            0  ./Managed
2018-04-04 14:10:46 .....         6656         6656  ./Managed/UnityEngine.AccessibilityModule.dll
2018-04-04 14:10:47 .....        30720        30720  ./Managed/UnityEngine.AIModule.dll
2018-04-04 14:10:47 .....        71168        71168  ./Managed/UnityEngine.AnimationModule.dll
2018-04-04 14:10:55 .....        20480        20480  ./Managed/UnityEngine.ARModule.dll
2018-04-04 14:10:52 .....         4608         4608  ./Managed/UnityEngine.AssetBundleModule.dll
```

so we could use 7z to install this
