### ISSUE TITLE
Latest versions not listed on linux

### ISSUE THREAD

**Issue by Dekedro** [DragonBox/u3d#256]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

According to [Unity3D forum](https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/page-2), latest versions of unity include 2017.2.1f1, 2017.3.1f1 and 2018.1.0b8. Sadly, I can't find these versions in `u3d available -f` and it is impossible to install them.
OS: Ubuntu 17.04

**Comment by lacostej** [comment]
We will look into this during the week!
