### ISSUE TITLE
Interactive version of u3d?

### ISSUE THREAD

**Issue by lacostej** [DragonBox/u3d#265]
`u3d -i` -> irb ?

See https://github.com/fog/fog/blob/master/bin/fog#L53 as an example

**Comment by niezbop** [comment]
That could be cool, but what would you actually do? Send calls to Unity (not sure if feasible)? Or extract infos from Unity to ruby?

But that does sound like an interesting feature, I'm just not sure there is a real usecase (at least in our case). It could be useful to setup some kind of server written in Unity?

**Comment by lacostej** [comment]
Access the API without having to make a git checkout of the exact version you have available.
