### ISSUE TITLE
New LTS releases not recognised

### ISSUE THREAD

**Issue by mattmurton** [DragonBox/u3d#276]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

Firstly, thanks for the great tool. We've integrated it into our Jenkins build process and it's proving extremely useful.
I have this week hit an issue...

Unity recently announced a [change to their release schedules](https://blogs.unity3d.com/2018/04/09/new-plans-for-unity-releases-introducing-the-tech-and-long-term-support-lts-streams/).
They plan to have Tech and LTS streams. The new LTS releases can currently be downloaded [from here](https://unity3d.com/unity/qa/lts-releases).

It seems u3d isn't finding these new versions.
I can't see `2017.4.1f1` or `2017.4.0f1` when running `u3d available`.

**Note:**
As a temporary workaround for anyone else with this issue, `u3d run` commands will still work with these releases if you install them manually using the folder naming conventions u3d expects.
e.g.
`Program Files/Unity_2017.4.1f1`

**Comment by lacostej** [comment]
Cool! Thanks for the bug report.

**Comment by lacostej** [comment]
The coming PR should allow to list and download / install the LTS versions. I haven't changed the listing  to clearly identify them, as this would require me to change the internal logic a bit. We don't really have a notion of channel and currently use the version number to differentiate between stable, betas and patches. Those LTS are just some special stable versions for now.
