### ISSUE TITLE
Unity Installations fail on Windows with space in path

### ISSUE THREAD

**Issue by KyleOrth** [DragonBox/u3d#302]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

When installing a new version of Unity, u3d will download the packages and put them in your user directory /Downloads/Unity_Packages/*** - however if the user directory has a space in it (e.g. C:/Users/John Smith/Downloads/Unity_Packages) the installation phase will fail. It seems that the downloading supports spaces in the file path, as the files were correctly downloaded to the right location, its just the install phase that doesn't work.

Have only tested on Windows, not sure if MacOS has the same issue.

**Comment by niezbop** [comment]
Hey @KyleOrth ! Thanks for raising this issue!

Would you mind sharing the error message(s) you are facing and such so that we can understand better your issue? Feel free to obfuscate any private piece of information ;)

**Comment by lacostej** [comment]
@niezbop 2 candidates 

https://github.com/DragonBox/u3d/blob/0b93044/lib/u3d/installer.rb#L343
https://github.com/DragonBox/u3d/blob/0b93044/lib/u3d/installer.rb#L350

where we don't escape the paths

**Comment by lacostej** [comment]
This seems fixed in next release. Try master version if you can't wait for the release. Thanks!
