### ISSUE TITLE
u3d run error: Not sure which version of Unity to run

### ISSUE THREAD

**Issue by DooblyNoobly** [DragonBox/u3d#309]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

Not sure what I'm doing wrong but I can't get u3d to work after installing version 2017.4.0f1 on ubuntu 16. 

I've read the readme 3-4 times. I checked out --help but still cannot figure it out. The Readme is pretty vague. I'm just trying to build a project from command line. I also cannot figure out how to set my username and password for the license. Appreciate any help. Thanks.

--trace output:
```
/var/lib/gems/2.3.0/gems/u3d-1.0.21/lib/u3d_core/ui/interface.rb:168:in `user_error!': Not sure which version of Unity to run. Are you in a Unity5 or later project? (U3dCore::Interface::UIError)
	from /var/lib/gems/2.3.0/gems/u3d-1.0.21/lib/u3d_core/ui/ui.rb:38:in `method_missing'
	from /var/lib/gems/2.3.0/gems/u3d-1.0.21/lib/u3d/commands.rb:203:in `run'
	from /var/lib/gems/2.3.0/gems/u3d-1.0.21/lib/u3d/commands_generator.rb:99:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-4.4.4/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-4.4.4/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-4.4.4/lib/commander/runner.rb:446:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/commander-4.4.4/lib/commander/runner.rb:68:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/u3d-1.0.21/lib/u3d/commands_generator.rb:253:in `run'
	from /var/lib/gems/2.3.0/gems/u3d-1.0.21/lib/u3d/commands_generator.rb:40:in `start'
	from /var/lib/gems/2.3.0/gems/u3d-1.0.21/exe/u3d:7:in `<top (required)>'
	from /usr/local/bin/u3d:22:in `load'
	from /usr/local/bin/u3d:22:in `<main>'
```

**Comment by niezbop** [comment]
> I also cannot figure out how to set my username and password for the license.

Not sure about this one. Maybe take a look at #282 and let's wait for @lacostej, I believe he'll be able to provide you with a bit more info on this than I could!

**Comment by lacostej** [comment]
@DooblyNoobly each unity project specifies the version of Unity it was last opened with (information stored under ProjectSettings/ProjectVersion.txt)

u3d needs to know which project you are opening before it can find out which version of Unity it needs to open. For that you need to tell u3d/Unity which project to open. Either you specify the location of your project using `-projectPath xxxxx` or you start u3d from within the project directory itself.

The error message you got: `Not sure which version of Unity to run. Are you in a Unity5 or later project?` tries to let you know that it couldn't find the Unity project and thus the required Unity version . We will improve the message.

Be familiar with https://docs.unity3d.com/Manual/CommandLineArguments.html as it contains the arguments you need to pass.

As for the username and password, given the above CLI, something like

```u3d -u 2017.4.1f1 -- -serial "xxxxxx" -username "xxxx" -password "xxxxx" -batchmode -quit -logFile `pwd`/editor.log```

should work

**Comment by DooblyNoobly** [comment]
Thanking you all! Choosing the version worked. Now I'm trying to figure out how to accept the license agreement without a display. Will close this issue now.
