### ISSUE TITLE
u3d available is not exhaustive

### ISSUE THREAD

**Issue by Danta1st** [DragonBox/u3d#312]
The list of available unity versions is not exhaustive.

A `u3d available -u 2017.3` yields the following results skipping the p2 version.

![image](https://user-images.githubusercontent.com/5593911/40535627-e831e098-6009-11e8-8687-1a7f50c8db77.png)

**Comment by lacostej** [comment]
@Danta1st good catch. I completely broke the pagination the other day. Doh!
