### ISSUE TITLE
Unity 2018.2.x is not listed as available

### ISSUE THREAD

**Issue by sp-ricard-valverde** [DragonBox/u3d#321]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

The latest Unity version, 2018.2.0f2 i believe, is not available through u3d.
It's not shown in the `available` command neither using `install latest` which still fetches the 2018.1.7f1 release.

**Comment by niezbop** [comment]
Hey! Thanks for your feedback. I'm investigating this.

Just for the sake of documenting the issue, it is available on windows but not on mac.
```
$ u3d available -u '2018'
Version 2018.1.0f2: https://download.unity3d.com/download_unity/d4d99f31acba/
Version 2018.1.1f1: https://download.unity3d.com/download_unity/b8cbb5de9840/
Version 2018.1.2f1: https://download.unity3d.com/download_unity/a46d718d282d/
Version 2018.1.3f1: https://download.unity3d.com/download_unity/a53ad04f7c7f/
Version 2018.1.4f1: https://download.unity3d.com/download_unity/1a308f4ebef1/
Version 2018.1.5f1: https://download.unity3d.com/download_unity/732dbf75922d/
Version 2018.1.6f1: https://download.unity3d.com/download_unity/57cc34175ccf/
Version 2018.1.7f1: https://download.unity3d.com/download_unity/4cb482063d12/
Version 2018.2.0f2: https://netstorage.unity3d.com/unity/787658998520/
```
```
$ u3d available -u '2018' -o mac
Version 2018.1.0f2: https://download.unity3d.com/download_unity/d4d99f31acba/
Version 2018.1.1f1: https://download.unity3d.com/download_unity/b8cbb5de9840/
Version 2018.1.2f1: https://download.unity3d.com/download_unity/a46d718d282d/
Version 2018.1.3f1: https://download.unity3d.com/download_unity/a53ad04f7c7f/
Version 2018.1.4f1: https://download.unity3d.com/download_unity/1a308f4ebef1/
Version 2018.1.5f1: https://download.unity3d.com/download_unity/732dbf75922d/
Version 2018.1.6f1: https://download.unity3d.com/download_unity/57cc34175ccf/
Version 2018.1.7f1: https://download.unity3d.com/download_unity/4cb482063d12/
```
This is an issue on our side, I'll take a quick look at it.

**Comment by niezbop** [comment]
The fix PR has been opened. You'll have to wait a bit for it to be merged and released but this should be done rather soon!

**Comment by sp-ricard-valverde** [comment]
Hey !

I've tested the fix by compiling the latest u3d `master` branch but the 2018.2 version it's still not there for mac :(.

<img width="567" alt="captura de pantalla 2018-07-12 a las 14 13 50" src="https://user-images.githubusercontent.com/3531261/42632634-1959f4e0-85de-11e8-9d36-dc474d086416.png">

**Comment by niezbop** [comment]
That's still normal, we're using an automated version fetcher which caches the versions online (https://dragonbox.github.io/unities/v1/versions.json). This hasn't been updated yet. I realized while working with this that we may want to have a way not to use it. It is going to get updated soon!

**Comment by sp-ricard-valverde** [comment]
Ok, my bad, I wasn't aware of this.

Thanks !

**Comment by niezbop** [comment]
No worries! This was not documented very well anyhow, so we have our share in this as well! Just to let you know, the 1.1.2 will be released soon, and the PR #324 has added a feature to bypass the central cache. If you compile locally now, you won't have to wait while the next version is released and the central cache gets updated! 😉

**Comment by sp-ricard-valverde** [comment]
Just as a side note, I had to remove the already locally cached file located in `/Users/ricardo/Library/Application Support/u3d/cache.json` for the `available` command to actually populate the cache again.
I would say that the `issue` is that the cache does not expire unless a couple of days have passed:
https://github.com/DragonBox/u3d/blob/cd0ca5dc14c165d0f4ca2601003a740536b6377d/lib/u3d/cache.rb#L102-L107

**Comment by niezbop** [comment]
You can force the refresh of the cache with the `-f/--force` option which will automatically refresh the cache 😉

From the `u3d available -h` help panel:
```
  OPTIONS:

    --[no-]central
        Use or not the central version cache

    -f, --force
        Force refresh list of available versions

    -r, --release_level STRING
        Checks for availability on specific release level [stable, beta, patch]

    -o, --operating_system STRING
        Checks for availability on specific OS [linux, mac, win]

    -u, --unity_version STRING
        Checks if specified version is available. Can be a regular expression

    -p, --packages
        Lists available packages as well
```
