### ISSUE TITLE
u3d available not listing all versions on macOS

### ISSUE THREAD

**Issue by bdominguez** [DragonBox/u3d#349]
I have u3d installed on both Windows and macOS machines set as slaves for Jenkins.

In my Windows machine it lists all 2018.3.x versions.

In my macOS machine it only lists (as of today) 2018.3.3 and 2018.3.7 versions.

I have tried to "gem uninstall u3d" "gem install u3d" "u3d available -f" with no results at all...

**Comment by niezbop** [comment]
Replicated on Mac for me

```
$ u3d available -f --no-central -u 2018.3.*
Cache is out of date. Updating cache for Mac OSX
Loading Unity lts releases
Found 23 lts releases.
Loading Unity stable releases
Found 109 stable releases.
Loading Unity patch releases
Found 191 patch releases.
Loading Unity latest releases
Found 8 latest releases.
Version 2018.3.3f1: https://download.unity3d.com/download_unity/393bae82dbb8/
Version 2018.3.7f1: https://download.unity3d.com/download_unity/9e14d22a41bb/
```

Thanks for raising the issue @bdominguez, we'll take a look at this at some point.

**Comment by lacostej** [comment]
@bdominguez thanks for the report. The bug is fixed. 

The cache builder is also using the latest version of u3d, meaning previous versions of u3d will get the proper list from the cache without having to update. Update is still recommended :)

Thanks again for the report!

**Comment by bdominguez** [comment]
Thanks!
