### ISSUE TITLE
I can't execute commands if I have an alpha version installed

### ISSUE THREAD

**Issue by bdovaz** [DragonBox/u3d#354]
Inspecting your code and specifically "PlaybackEngineUtils.list_module_configs" I see that it's because in 2019.2.x alpha there is no "ivy.xml" under (at least in alpha 8): Editor\Data\PlaybackEngines\{platform}\ivy.xml

My problem is because it blocks on using u3d if I have an alpha version installed.

**u3d install 2018.3.9f1 --trace**
```
Traceback (most recent call last):
        16: from C:/Ruby26-x64/bin/u3d:23:in `<main>'
        15: from C:/Ruby26-x64/bin/u3d:23:in `load'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/exe/u3d:7:in `<top (required)>'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:40:in `start'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:260:in `run'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:173:in `block (2 levels) in run'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/lib/u3d/commands.rb:159:in `install'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/lib/u3d/commands.rb:344:in `check_unity_presence'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/lib/u3d/commands.rb:344:in `find'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/lib/u3d/commands.rb:344:in `each'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/lib/u3d/commands.rb:344:in `block in check_unity_presence'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.1.5/lib/u3d/installation.rb:352:in `version': **Couldn't find a module under C:/Program Files/Unity_2019.2.0a8/Editor/Data/ (RuntimeError)**
```

**Comment by lacostej** [comment]
We will have to look at how modules are installed & identified in those versions.

@bdovaz did you install this version using u3d?

**Comment by lacostej** [comment]
I installed `2019.2.0a9` using u3d. It looks like we could use `.*.Extensions.dll` to detect already installed modules instead of the `ivy.xml` files. It looks like it could be backward compatible with former versions as well. I'll dig a bit more before changing the whole implementation.

**Comment by lacostej** [comment]
I'll need a Windows box to change the full implementation. In particular we will need a way to detect the Unity version of a particular Installation.

**Comment by bdovaz** [comment]
Thank you and don't be in a hurry, it's just so you know there's a problem with 2019.2.x alpha.

**Comment by thyjukki** [comment]
Any update on this? Our test automation currently does not work when we updated to 2019.2 beta.

**Comment by tom-fv** [comment]
Now that 2019.2 is out of beta, this has become a problem for us as we need to use the latest tool, might try and have a look at the issue myself in the source, but.....I'm not very experiences in ruby...at alll
