### ISSUE TITLE
u3d can't list all available versions for Linux

### ISSUE THREAD

**Issue by yusdacra** [DragonBox/u3d#360]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

I have tried `u3d available` with and without --no-central. It only lists up to 2019.1.0f2. There is a LTS build not shown, 2018.4.0f1. And there are some other builds 2019.2.0b2 and 2019.3.0a2. Builds i mentioned are available from [https://public-cdn.cloud.unity3d.com/hub/prod/releases-linux.json](url)

**Comment by KonH** [comment]
It looks like I've faced with the same issue.
