### ISSUE TITLE
When using prettifier, have an option to write the raw log to file in case we need it

### ISSUE THREAD

**Issue by oddgames-david** [DragonBox/u3d#365]
There are times when an error isn't captured due to outdated rules or a weird scenario.

I'd like to be able to output the raw logs to file in case I need to reference them

**Comment by niezbop** [comment]
Hey @oddgames-david !

This is already possible with u3d 😄 You can pass arguments to Unity, including [-logFile](https://docs.unity3d.com/Manual/CommandLineArguments.html) which tells Unity to put its raw log at a specific place. The way you can do this is by adding `-- <your Unity args>`, for example we at Dragonbox run something like: `u3d -- -logFile raw.log`.

Hope this helps!

On a sidenote, you can create your own set of logging rules if you're not satisfied with u3d's, but I'll explain this on #362 you other PR 😃
