### ISSUE TITLE
unity 2019.2.x on windows

### ISSUE THREAD

**Issue by pauWin** [DragonBox/u3d#367]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

I have an installation error when I try to install 2019.2.0f1 on windows
Steps:
1. u3d install 2019.2.0f1
2. u3d run -u 2019.2.0f1 --trace

Error: 
```
Traceback (most recent call last):
	16: from C:/Ruby25-x64/bin/u3d:23:in `<main>'
	15: from C:/Ruby25-x64/bin/u3d:23:in `load'
	14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/exe/u3d:7:in `<top (required)>'
	13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:40:in `start'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:260:in `run'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/lib/u3d/commands_generator.rb:99:in `block (2 levels) in run'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/lib/u3d/commands.rb:212:in `run'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/lib/u3d/commands.rb:344:in `check_unity_presence'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/lib/u3d/commands.rb:344:in `find'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/lib/u3d/commands.rb:344:in `each'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/lib/u3d/commands.rb:344:in `block in check_unity_presence'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/u3d-1.1.5/lib/u3d/installation.rb:353:in `version': Couldn't find a module under C:/Program Files/Unity_2019.2.0f1/Editor/Data/ (RuntimeError)
```

The installation seems to run ok but when I try to run unity it doesn't parse the version number.
I'm getting the same result when I tried to install 2019.2.1f1.
Installing 2018.x seems to work fine though. 

Thanks.

**Comment by mwegner** [comment]
Well, I did a quick rummage, and don't see a fast/easy way to patch in support for discovering versions/modules.  I didn't spend very long hunting, though, because I realized the quick-and-dirty solution is to just to place an `ivy.xml` file in the 2019.2.2f1 folder myself:

```<?xml version="1.0" encoding="utf-8"?>
<ivy-module version="2.0">
  <info version="2019.2.2" organisation="Unity" module="StandaloneWindows" e:packageType="PlaybackEngine" e:unityVersion="2019.2.2f1" xmlns:e="http://ant.apache.org/ivy/extra" />
  <publications xmlns:e="http://ant.apache.org/ivy/extra">
    <artifact name="UnityEditor.WindowsStandalone.Extensions" type="dll" ext="dll" />
  </publications>
</ivy-module>
```

Place in `C:\Program Files\Unity_2019.2.2f1\Editor\Data\PlaybackEngines\windowsstandalonesupport`, and I guess in whatever other platforms are installed. I'm only using this Windows build machine for Windows builds, so didn't test behavior there.

A bit of a pain, so ideally it gets fixed properly soon.  u3d completely breaks with a 2019.2 version installed--not just operations targeting 2019.2, but all invocations (install/list/etc).

Hopefully the above hack helps anyone else who bumps into the problem in the meantime...

**Comment by Ygdrassil** [comment]
Thank you @mwegner 
I was thinking the same thing. A temporary solution for now.

**Comment by pauWin** [comment]
Thanks for the work around for now. Will try that out!

**Comment by bdominguez** [comment]
+1

@lacostej Please, fix this. It's not usable in 2019.x versiones on CI environments where all it's automated.

**Comment by niezbop** [comment]
Hey everyone.
This has been adressed an will be released shortly. Thanks for your patience.

**Comment by bdominguez** [comment]
Thanks @niezbop !
