### ISSUE TITLE
How to run on windows?

### ISSUE THREAD

**Issue by dimmduh** [DragonBox/u3d#368]
Can not see any exe file on root or something I can run.Pls, help

**Comment by niezbop** [comment]
Hey @dimmduh !

`u3d` is a [Ruby gem](https://rubygems.org/), which means that as long as you have Ruby installed on your Windows machine all you have to do is `gem install u3d`, [as specified in the README](https://github.com/DragonBox/u3d#installation).

Note that we also a few [recommendations on how to install Ruby on your Windows machine](https://github.com/DragonBox/u3d#install-ruby) in the README!
