### ISSUE TITLE
New linux versions are not visible in u3d

### ISSUE THREAD

**Issue by galeksic90** [DragonBox/u3d#369]
Hello,

Unity Linux has officially released and they moved from forum links to Unity Hub.
Currently the latest version with u3d is 2019.1.0f2, which is beta.

On the other hand Unity Hub lists 'official releases' and the latest version is 2019.2.9f1.

Are you planning to update the links for newer versions of unity or we should move to Unity hub?

**Comment by niezbop** [comment]
Hey @galeksic90 

This issue has been addressed with #364 It hasn't been released yet, but we're planning to release it soon. We'll keep you up to date.

Local builds works 😄 
```
paulniezborala@Pauls-MacBook-Pro u3d (master) $ u3d available -o linux --no-central --force -u 2019.*
Cache is out of date. Updating cache for Linux
Loading Unity releases
Loading Unity latest releases
Found 8 latest releases.
Found 92 releases.
Version 2019.1.0f2: http://beta.unity3d.com/download/292b93d75a2c/
Version 2019.1.14f1: https://download.unity3d.com/download_unity/148b5891095a/
Version 2019.2.11f1: https://download.unity3d.com/download_unity/5f859a4cfee5/
Version 2019.3.0b9: https://beta.unity3d.com/download/de32b4c0dd7a/
```

**Comment by galeksic90** [comment]
Hi @niezbop 

Great, as i can see the pull request is made on 4 July which 4 months ago, are you planning to release it this month?

**Comment by niezbop** [comment]
Yep. I'm not sure exactly why we didn't release this sooner.

We're trying to fit a couple of fixes into this release, but you can't definitely expect it this month. Thanks for your patience.

**Comment by galeksic90** [comment]
@niezbop 

Ok, can i build u3d myself and expect to see new versions?

**Comment by niezbop** [comment]
@galeksic90 Sure thing. Nevertheless, there are a few things to be mindful of when building locally: the central cache will not be up-to-date so you'll have to run `u3d available --no-central --force` to make sure that you fetch them yourself.

Otherwise, you can run `./build.sh` locally to handle the gem building.

Let me know if that did the trick, I'll close the issue for now!
