### ISSUE TITLE
u3d list command does not work in non-standard path

### ISSUE THREAD

**Issue by bdovaz** [DragonBox/u3d#370]
I have previously installed a version of the editor with this command:

`u3d install 2019.2.11f1 -p Android --installation_path "E:\Unity2019.2.11f1"`

I tried to list the installed versions of Unity and it tells me that there is none and I see in the code that it is because it only searches the default paths set by u3d.

https://github.com/DragonBox/u3d/blob/c4a01f8c8b6ded2877471b43360eeb4bc617a72e/lib/u3d/installer.rb#L365

I understand that in the "list" command should have an option to pass one or several different paths where to search.

Something like this:

`u3d list --paths "E:/Unity" "C:/Program Files/"`

**Comment by niezbop** [comment]
This causes issue #371 

Thanks for bringing this up to our attention. This is actually an issue which is not Windows-specific but cross-platform. I will be opening a PR with a solution for this, feel free to jump on it to talk about it.
