### ISSUE TITLE
installation_path parameter problems

### ISSUE THREAD

**Issue by bdovaz** [DragonBox/u3d#371]
This command works correctly:

`u3d install 2019.2.11f1 --installation_path "E:\Unity2019.2.11f1"`

If I run the same command again it reinstalls it instead of saying it is already installed.

Also if I want to install a module in the same path later it is impossible for me.

`u3d install 2019.2.11f1 -p Android --installation_path "E:\Unity2019.2.11f1"`

I get the following error:

`Please install Unity before any of its packages`

I don't know if it's related to this other bug:

#370

**Comment by niezbop** [comment]
Hey @bdovaz ! Thanks for raising this issue to our attention!

This is indeed due to #370, I'll answer on the other issue!

**Comment by niezbop** [comment]
Hey @bdovaz! Just to let you know that we started tackling this issue, and we're trying to design a good solution for this issue.

My current proposition is to introduce an environment variable to specify the additional paths, but we're pondering whether this is a good idea.

We'd love your input if you have some time to discuss this issue regarding the best way to tackle that, so feel free to leave a comment on #374!

**Comment by bdovaz** [comment]
Thanks @niezbop !

**Comment by niezbop** [comment]
Heyo @bdovaz ! The solution to this will be in the next release! Thanks a lot for your feedback
