### ISSUE TITLE
[Windows] Unable to load password for automated installation

### ISSUE THREAD

**Issue by KyleOrth** [DragonBox/u3d#386]
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

I have been unsuccessful in getting Windows to be able to install using u3d without running as an administrator. I have tried using the documentation suggesting to use the U3D_PASSWORD variable.

Copying the example in Jenkins directly from https://github.com/DragonBox/u3d/blob/master/docs/ci_setup.md didn't work for me. Also trying a bunch of combinations setting a system environment variable, or calling `set U3D_PASSWORD=password` before running u3d install, but nothing seems to be working for me.

This is the output I end up getting every time:

```
u3d install 2018.4.12f1 --trace --verbose
DEBUG Loading modules for version 2018.4.12f1
DEBUG Looking for installed Unity version under C:/Program Files/
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.2.1/lib/u3d/installation.rb:324: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
DEBUG Version 2018.4.12f1 of Unity is not installed yet
WARN Root privileges are required
Traceback (most recent call last):
        12: from C:/Ruby26-x64/bin/u3d:23:in `<main>'
        11: from C:/Ruby26-x64/bin/u3d:23:in `load'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.2.1/exe/u3d:7:in `<top (required)>'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.2.1/lib/u3d/commands_generator.rb:40:in `start'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.2.1/lib/u3d/commands_generator.rb:260:in `run'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.2.1/lib/u3d/commands_generator.rb:173:in `block (2 levels) in run'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.2.1/lib/u3d/commands.rb:165:in `install'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/u3d-1.2.1/lib/u3d/commands.rb:429:in `get_administrative_privileges': Could not get administrative privileges (RuntimeError)
```

It will install perfectly fine if I run the command window as an administrator.

**Comment by lacostej** [comment]
Could you try opening `u3d console` and doing

`U3dCore::CommandExecutor.has_admin_privileges?`

Type your password when requested

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/24282/69313395-b3575f80-0c31-11ea-9da5-cbe71f53402f.png">

Paste the output. Thanks

**Comment by KyleOrth** [comment]
I don't get any prompt to enter a password - the command seems to be echoed back to me, then it leaves interactive mode. Full text:

```
Jenkins@ALIENWARE2 MINGW64 ~
$ u3d console
Switch to inspect mode.
Welcome to u3d interactive!
>> U3dCore::CommandExecutor.has_admin_privileges?
U3dCore::CommandExecutor.has_admin_privileges?

Jenkins@ALIENWARE2 MINGW64 ~
$
```

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1870757/69327878-5e9ffd00-0ca2-11ea-9954-952c7f2e8a58.png">

**Comment by KyleOrth** [comment]
As an update, if I run the same command in a windows command prompt (instead of git bash window, as per my previous reply), I get the following output (still not asked for my password, immediately replies with false)

```
Microsoft Windows [Version 10.0.18363.476]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Jenkins>u3d console
Welcome to u3d interactive!
>> U3dCore::CommandExecutor.has_admin_privileges?
false
>>
```

![image](https://user-images.githubusercontent.com/1870757/69328150-d5d59100-0ca2-11ea-8124-8fdd5b29f825.png)


If I run it on my Mac, it asks for my password and after entering it returns true, like in your screenshot.

**Comment by niezbop** [comment]
Hey @KyleOrth !

Just chiming in to let you know that this is documented in our [README](https://github.com/DragonBox/u3d/blob/master/README.md#security).

> Security
> 
> When you install Unity with this tool, you will have to grant it higher privileges so it can perform the installation. It means that under MacOS and Linux, you will be asked for your sudo password.
> 
> On Windows, you must launch an administrative command interface to be able to run install without the --no-install option. Same goes for any kind of sanitization where u3d would move files around.

We have tried several different things to get admin privileges with a standard console, but this is not something that we managed to get working. I'm not sure that this is doable at all on Windows and I don't have any example of applications acquiring admin privileges through password on this platform, as would be doable on Unix.

**Comment by KyleOrth** [comment]
Thanks for the update @niezbop - I did see that in the README, but also noticed the setup explained to work-around needing to run as an administrator by using the U3D_PASSWORD as documented on the [CI Setup](https://github.com/DragonBox/u3d/blob/master/docs/ci_setup.md) page.

It might be out of date though - I'll proceed with the assumption that an admin command interface is needed for installs on Windows (unless any extra tips / things to try come up).

**Comment by niezbop** [comment]
I think that the CI Setup page may only be valid for Linux or Mac. Our CI build pipeline is based on Mac agents here at DragonBox.

> I'll proceed with the assumption that an admin command interface is needed for installs on Windows (unless any extra tips / things to try come up)

I think that this is a correct assumption. As far as I know, we didn't find a way to install on Windows without an admin terminal.

**Comment by niezbop** [comment]
If that's okay with you, I'll close the issue for now. We may reopen it if we find a way to bypass the need for the admin interface or find a workaround that should be documented, but for the time being, there's not much we can do!

**Comment by KyleOrth** [comment]
Ah I just assumed the CI Server was talking about Windows for some reason... but the sample has a Jenkins slave called Mac. My mistake for misunderstanding there. Thanks for the response @niezbop

**Comment by niezbop** [comment]
With pleasure @KyleOrth. Maybe we could clarify the CI Setup documentation though.

**Comment by lacostej** [comment]
@niezbop WRT elevating windows priveleges, I just found this: https://social.technet.microsoft.com/Forums/windows/en-US/132e170f-e3e8-4178-9454-e37bfccd39ea/startprocess-verb-runas-amp-credential?forum=winserverpowershell
