### ISSUE TITLE
github releases are not marked as latest nor contain changelogs

### ISSUE THREAD

**Issue by lacostej** [DragonBox/u3d#389]
I wanted to reuse fastlane's updatechecker. The changelog feature doesn't work as we don't tag our releases fully on github. rubygems doesn't contain the changelog either.

**Comment by niezbop** [comment]
Yup. That's because there's no release, but only tags! I noticed that when releasing 1.2*

We should adapt our release pipeline to create a release as we do for Uplift

**Comment by lacostej** [comment]
For reference: https://github.com/fastlane/fastlane/blob/master/fastlane/Fastfile#L251-L280 and https://github.com/DragonBox/uplift/blob/master/DevelopmentTools/Rakefile#L144-L219
