### ISSUE TITLE
Document installation path sanitization

### ISSUE THREAD

**Issue by lacostej** [DragonBox/u3d#50]
Feedback:

> When I run u3d list it first told me that it needed to move my 20 unity installations. Where does it
> want to move them and why? They are currently all residing in the Applications folder as
> "Unity5_3_8f2" and so on up to and including "Unity2017_1_f3". I couldn't find anywhere in the
> readme where it wanted them to go.

Let's improve this:

- [ ] update the README with why and how path sanitization works, interactive mode etc.
- [ ] update inline help
- [ ] maybe update u3d to point to README

**Comment by Skjalgsm** [comment]
While I like the list of improvements, I also think that renaming Applications/Unity5_3_8f2 to Applications/Unity_5.3.8f2 will bite you in the ass sometime later as dots (.) in paths makes me shiver :) Is this something that is supported on mac and not windows perhaps?

**Comment by lacostej** [comment]
@Skjalgsm Supported on Linux/Mac/Windows **If** the already installed versions are discovered.

On Mac we use the finder. On Linux, we search in a specific place, on Windows I forgot :) @niezbop knows!
