### ISSUE TITLE
Installation stays in /Application/Unity when installing on OSX

### ISSUE THREAD

**Issue by exlee** [DragonBox/u3d#68]
When installing Unity version from `u3d` the installation stays in `/Application/Unity` and requires additional `u3d` loop in order for installation to be moved to proper versioned directory even though it asks for the elevated permissions.

No errors or warning are shown during the installation.

**Comment by niezbop** [comment]
Working as intended on master. Bug related to 0.9.3 I guess. Closing the issue for now.

**Comment by niezbop** [comment]
Needs to be tested further.
